# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

#pipeline:
#- name: WhitespaceTokenizer
#- name: RegexFeaturizer
#- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
#- name: CountVectorsFeaturizer
#  analyzer: char_wb
#  min_ngram: 1
#  max_ngram: 4
#- name: DIETClassifier
#  epochs: 100
#  constrain_similarities: true
#- name: EntitySynonymMapper
#- name: FallbackClassifier
#  threshold: 0.2
#  ambiguity_threshold: 0.05


pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer  # Pretrained embeddings
  model_name: "bert"    #Note: Bert has 512 token limit on responses. Some responses like workshop one is ~800 tokens
#- name: "custom_components.longformer_featurizer.CustomLongformerFeaturizer"
#  model_name: "allenai/longformer-base-4096"
  #max_length: 1024
  #model_weights: "xlnet-small"
  #max_length: 512
  #batch_size: 1
#- name: CountVectorsFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexFeaturizer # Useful for patterns like phone nums, emails etc.
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  batch_size: [64, 128] # Lower this range if low on memory
  learning_rate: 0.001
  embedding_dimension: 150
  transformer_size: 256
- name: FallbackClassifier
  threshold: 0.2
  ambiguity_threshold: 0.005
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq
  constrain_similarities: true

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
assistant_id: 20250305-191431-primordial-quiver
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   #- name: MemoizationPolicy
   #- name: RulePolicy
   #- name: UnexpecTEDIntentPolicy
   #  max_history: 5
   #  epochs: 100
   #- name: TEDPolicy
   #  max_history: 5
   #  epochs: 100
   #  constrain_similarities: true

#action_endpoint:
  #url: "http://localhost:5005/webhook"
